/**
 * Interface representing a Task object returned by the API.
 * id: Unique integer identifier generated by SQLite (AUTOINCREMENT).
 * title: Non-empty string description of the task.
 * done: Boolean flag indicating completion status.
 */
export interface Task {
  id: number;
  title: string;
  done: boolean;
}

/**
 * DTO for creating a new Task.
 * title: Required task title.
 * done: Optional boolean flag (defaults to false if omitted).
 */
export interface CreateTaskDTO {
  title: string;
  done?: boolean;
}

/**
 * DTO for updating an existing Task.
 * title: Optional new title.
 * done: Optional new done status.
 */
export interface UpdateTaskDTO {
  title?: string;
  done?: boolean;
}

/**
 * Database row shape returned directly by better-sqlite3 queries before mapping.
 * SQLite stores BOOLEAN values as 0 (false) or 1 (true) integers.
 */
export interface TaskDbRow {
  id: number;
  title: string;
  done: number | boolean;
}
